version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root  # Keep the root password
      MYSQL_DATABASE: kartverketdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kartverket-network

networks:
  kartverket-network:
    external: true
